### ISSUE TITLE
Update pipeline notebook with new pipeline names

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/nircam_calib#21]
For @aliciacanipe 
e.g. sloper pipeline is now calwebb_detector1.

Also would be helpful to show how to override individual step values when calling a pipeline. Here's an example I put together the other day after talking with Howard and James.

    from jwst.pipeline import calwebb_detector1
    m = calwebb_detector1.Detector1Pipeline(config_file='calwebb_detector1.cfg')
    m.saturation.override_saturation = 'mysatfile.fits'
    m.superbias.override_superbias = 'mysuperbias.fits'
    m.refpix.odd_even_rows = False
    m.group_scale.skip = True
    m.ipc.skip = True
    m.dark_current.skip = True
    m.persistence.skip = True
    m.output_file = outfile
    m.run('myrawfile_uncal.fits')

**Comment by aliciacanipe** [comment]
Made some changes to the JWST pipeline notebook:

1. Edited it to reflect recent pipeline updates.
2. Added information on how to override individual steps when calling a pipeline.
3. Added a note about multiprocessing to batch-process multiple files.
