### ISSUE TITLE
Pipeline calls: cfg files and call vs run

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/nircam_calib#79]
James Davies tells me that the only way to use config files (or more accurately, the only way that the pipeline pays attention to config files) is when you call the pipeline from the command line (`strun`) or when you use the `call` method. The `run` method just looks for default values and values set by the user, but ignores cfg files.

I've only looked at the level 3 pipeline notebook, but in there the config files are used with `run`, which we saw at a recent hack day didn't work well. 

We should check the existing notebooks and make updates anywhere they are needed.

**Comment by aliciacanipe** [comment]
Oh yeah, I remembered being very confused by this before. I hadn't realized when I wrote the walkthrough that any config files I was specifying were getting ignored altogether. James and I were talking about this here: https://jira.stsci.edu/browse/JP-307 but I forgot to update the notebooks afterwards. I'll fix them.

**Comment by aliciacanipe** [comment]
I think my notebooks are the only ones that had this notation? I'll go ahead and close this, I think I've fixed all the occurrences with the incorrect notation now.
